appWeathery/urls.py
from django.urls import path
from . import views

app_name = 'appWeathery'

urlpatterns = [
    path('', views.home, name='home'),
    path('updateMap/', views.update_map, name='update_map')
]

projectWeather/urls.py
from django.contrib import admin
from django.urls import path, include
from appWeathery import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(urls))
]

appWeathery/models.py
from django.db import models

# Create your models here.

appWeathery/views.py
from django.shortcuts import render
from django.http import JsonResponse
from opencage.geocoder import OpenCageGeocode
from dotenv import load_dotenv
import os
import requests
from .request_placa import send_command

def home(request):
    return render(request, 'appWeathery/home.html')


def update_map(request):
    if request.method == 'GET':
        city    =  request.GET.get('city')
        state   =  request.GET.get('state')
        query   =  f'{city}, {state}, Brasil'

        load_dotenv()

        OPEN_CAGE_API_KEY   =  os.getenv('OPEN_CAGE_API_KEY', 'change-me')
        geocoder            =  OpenCageGeocode(OPEN_CAGE_API_KEY)
        results             =  geocoder.geocode(query)
        lat                 =  results[0]['geometry']['lat']
        lng                 =  results[0]['geometry']['lng']
        lang                =  'pt_br'

        OPEN_WEATHER_API_KEY    =  os.getenv('OPEN_WEATHER_API_KEY', 'change-me')
        url_request             =  f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lng}&appid={OPEN_WEATHER_API_KEY}&lang={lang}"
        datas_weather           =  requests.get(url_request).json()

        temp_max_celsius        =  round(datas_weather['main']['temp_max'] - 273, 2)
        temp_min_celsius        =  round(datas_weather['main']['temp_min'] - 273, 2)
        temperature_celsius     =  round(datas_weather['main']['temp'] - 273, 2)

        weather_info = {
        'city':         datas_weather['name'],
        'icon':         datas_weather['weather'][0]['icon'],
        'state':        state,
        'country':      datas_weather['sys']['country'],
        'humidity':     datas_weather['main']['humidity'],
        'pressure':     datas_weather['main']['pressure'],
        'temp_min':     temp_min_celsius,
        'temp_max':     temp_max_celsius,
        'temperature':  temperature_celsius,
        'description':  datas_weather['weather'][0]['description'],
        }

        humidity = float(datas_weather['main']['humidity'])
        
        if humidity > 60:
            send_command("LED_GREEN")
        else:
            send_command("LED_RED")
            

        response = JsonResponse({'lat': lat, 'lng': lng, 'weather_info': weather_info})
        return response

appWeathery/templates/appWeathery/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weather Dashboard</title>

    <!-- Leaflet CSS -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" 
        integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" 
        crossorigin=""/>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
    <!-- App CSS -->
    <link rel="stylesheet" href="{% static 'css/stylesHome.css' %}">
</head>
<body>
    <header class="bg-primary text-white py-3">
        <div class="container">
            <nav class="d-flex justify-content-between align-items-center">
                <h1 class="h3">Weather Dashboard</h1>
                <!-- Formulário de Busca -->
                <form class="row g-2" hx-get="{% url 'appWeathery:update_map' %}" hx-trigger="submit" 
                      hx-target="#map-container" hx-swap="none">
                    {% csrf_token %}
                    <div class="col-auto">
                        <label for="city">City:</label>
                        <input type="search" name="city" id="city" required placeholder="Enter city">

                        <label for="state">State:</label>
                        <input type="search" name="state" id="state" required placeholder="Enter state">

                        <button type="submit"  class="btn btn-light">Submit</button>
                    </div>
                </form>
            </nav>
        </div>
    </header>

    <main class="container mt-4">
        <!-- Contêiner do Mapa -->
        <section id="map-container" class="mb-4">
            <div id="map" class="rounded shadow" style="height: 400px;"></div>
        </section>

        <!-- Contêiner de Informações Climáticas -->
        <section id="weather-container" class="bg-light p-4 rounded shadow">
            <h2 id="cityName" class="text-center text-primary" aria-live="polite" role="status">Weather Info</h2>
            <div class="mt-4">
                <!-- Conteúdo dinâmico será inserido aqui -->
            </div>
        </section>
    </main>

    <!-- Leaflet JS -->
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" 
        integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" 
        crossorigin=""></script>
    
    <!-- htmx -->
    <script src="https://unpkg.com/htmx.org@2.0.4" 
        integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+" 
        crossorigin="anonymous"></script>
    
    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    
    <!-- App Scripts -->
    <script src="{% static 'js/map.js' %}"></script>
    <script src="{% static 'js/datas_weather.js' %}"></script>

</body>
</html>